export const groups = [
    { cod: 0, title: 'Peitoral'},
    { cod: 1, title: 'Dorsais'},
    { cod: 2, title: 'Deltóides'},
    { cod: 3, title: 'Trapézio'},
    { cod: 4, title: 'Tríceps'},
    { cod: 5, title: 'Bíceps'},
    { cod: 6, title: 'Antebraço'},
    { cod: 7, title: 'Coxas'},
    { cod: 8, title: 'Glúteos'},
    { cod: 9, title: 'Panturrilhas'},
    { cod: 10, title: 'Core'},
    { cod: 11, title: 'Técnica avançada'}
];

export const videos = [
    { title: 'Supino Reto Barra', video: 'https://www.youtube.com/watch?v=sqOw2Y6uDWQ', group: 0},
    { title: 'Supino Reto Halteres', video: 'https://www.youtube.com/watch?v=Spbmm66NsuY', group: 0},
    { title: 'Supino Reto Smith', video: 'https://www.youtube.com/watch?v=b-THwNtIYxY', group: 0},
    { title: 'Supino Inclinado Barra', video: 'https://www.youtube.com/watch?v=lBCjPgnIzKk', group: 0},
    { title: 'Supino Inclinado Halteres', video: 'https://www.youtube.com/watch?v=Z1rCZ0YHrP0', group: 0},
    { title: 'Supino Inclinado Smith', video: 'https://www.youtube.com/watch?v=L4kIk2gMeBw', group: 0},
    { title: 'Supino Declinado Barra', video: 'https://www.youtube.com/watch?v=hZ9woVlzGdA', group: 0},
    { title: 'Supino Declinado Halteres', video: 'https://www.youtube.com/watch?v=0SFB2chQTPY', group: 0},
    { title: 'Supino Declinado Smith', video: 'https://www.youtube.com/watch?v=xLQ9ZbH9ljc', group: 0},
    { title: 'Crucifixo Reto Halteres', video: 'https://www.youtube.com/watch?v=dQi36EfA88c', group: 0},
    { title: 'Crucifixo Inclinado Halteres', video: 'https://www.youtube.com/watch?v=4JvT5Ys1Bog', group: 0},
    { title: 'Crucifixo Declinado Halteres', video: 'https://www.youtube.com/watch?v=QsZ8VYaRh34', group: 0},
    { title: 'Cross-Over Polia Alta', video: 'https://www.youtube.com/watch?v=HNUji0rHFCs', group: 0},
    { title: 'Cross-Over Polia Média', video: 'https://www.youtube.com/watch?v=iLRFLm82dbg', group: 0},
    { title: 'Cross-Over Polia Baixa', video: 'https://www.youtube.com/watch?v=Jy_hZnK-_lo', group: 0},
    { title: 'Crucifixo Na Máquina', video: 'https://www.youtube.com/watch?v=Ru9OVOUlp0U', group: 0},
    { title: 'Peck Deck ou Crucifixo Na Máquina', video: 'https://www.youtube.com/watch?v=Ru9OVOUlp0U', group: 0},
    { title: 'Flexão De Braço', video: 'https://www.youtube.com/watch?v=F9FC_KBsLpY', group: 0},
    { title: 'Barra Fixa Peg Pronada', video: 'https://www.youtube.com/watch?v=JX_YM7Bp26U', group: 1},
    { title: 'Barra Fixa Peg Supinada', video: 'https://www.youtube.com/watch?v=WJOu_aru3XM', group: 1},
    { title: 'Barra Fixa Com Triângulo', video: 'https://www.youtube.com/watch?v=uCnmHgHgfOs', group: 1},
    { title: 'Levantamento Terra', video: 'https://www.youtube.com/watch?v=T3x53s0jEns', group: 1},
    { title: 'Puxada Vertical Peg Pronada', video: 'https://www.youtube.com/watch?v=H09EvebBsB4', group: 1},
    { title: 'Puxada Vertical Peg Supinada', video: 'https://www.youtube.com/watch?v=v1rPzvJvwIE', group: 1},
    { title: 'Puxada Vertical Com Triângulo', video: 'https://www.youtube.com/watch?v=ej9Z_jMQpLY', group: 1},
    { title: 'Remada Curvada Peg Pronada', video: 'https://www.youtube.com/watch?v=XruycmUNi1Y', group: 1},
    { title: 'Remada Curvada Peg Supinada', video: 'https://www.youtube.com/watch?v=y-XZnuKx3Q0', group: 1},
    { title: 'Remada Curvada Cavalinho', video: 'https://www.youtube.com/watch?v=Hdqf7mlEHrA', group: 1},
    { title: 'Remada Curvada Halteres Peg Pronada', video: 'https://www.youtube.com/watch?v=AT8pPML17VU', group: 1},
    { title: 'Remada Curvada Halteres Peg Supinada', video: 'https://www.youtube.com/watch?v=g0VduhIsJIE', group: 1},
    { title: 'Remada Curvada Halteres Peg Neutra', video: 'https://www.youtube.com/watch?v=CyCkDYs49hM', group: 1},
    { title: 'Remada Máquina Peg Pronada', video: 'https://www.youtube.com/watch?v=_g6GeyWVivI', group: 1},
    { title: 'Remada Máquina Peg Supinada', video: 'https://www.youtube.com/watch?v=1CG-dreRL6Q', group: 1},
    { title: 'Remada Máquina Peg Neutra', video: 'https://www.youtube.com/watch?v=C0-C0X7G8eQ', group: 1},
    { title: 'Remada Cross Peg Pronada', video: 'https://www.youtube.com/watch?v=IA0SRm2mY9M', group: 1},
    { title: 'Remada Cross Peg Supinada', video: 'https://www.youtube.com/watch?v=Q5Rl_fnOCBs', group: 1},
    { title: 'Remada Cross Peg Neutra', video: 'https://www.youtube.com/watch?v=wC1EsDy_esM', group: 1},
    { title: 'Remada Unilateral Peg Pronada', video: 'https://www.youtube.com/watch?v=VlCc-rDbwhA', group: 1},
    { title: 'Remada Unilateral Peg Supinada', video: 'https://www.youtube.com/watch?v=MAHNlcA4oXc', group: 1},
    { title: 'Remada Unilateral Peg Neutra', video: 'https://www.youtube.com/watch?v=C-tlPEhjwTk', group: 1},
    { title: 'Pull-Down Barra', video: 'https://www.youtube.com/watch?v=qw37xEEcoig', group: 1},
    { title: 'Pull-Down Cross Peg Pronada', video: 'https://www.youtube.com/watch?v=EG1ua8lDQJA', group: 1},
    { title: 'Pull-Down Cross Peg Supinada', video: 'https://www.youtube.com/watch?v=U80znmkD2z0', group: 1},
    { title: 'Pull-Down Cross Corda', video: 'https://www.youtube.com/watch?v=zdLHXB9Sn88', group: 1},
    { title: 'Elevação Lateral Halteres', video: 'https://www.youtube.com/watch?v=89K5H0Vvhnw', group: 2},
    { title: 'Elevação Lateral Sentado Halteres', video: 'https://www.youtube.com/watch?v=esWhjFJMNtU', group: 2},
    { title: 'Elevação Lateral Cross Posterior', video: 'https://www.youtube.com/watch?v=I-ywK8Q-9TM', group: 2},
    { title: 'Elevação Lateral Cross Anterior', video: 'https://www.youtube.com/watch?v=8KOat8ZsidI', group: 2},
    { title: 'Elevação Lateral Unilateral Banco Inclinado', video: 'https://www.youtube.com/watch?v=8s9JRhE95mU', group: 2},
    { title: 'Elevação Frontal Barra Peg Pronada', video: 'https://www.youtube.com/watch?v=jXUIrrvlR_0', group: 2},
    { title: 'Elevação Frontal Barra Peg Supinada', video: 'https://www.youtube.com/watch?v=Ea_8qpcysYI', group: 2},
    { title: 'Elevação Frontal Halteres Peg Pronada', video: 'https://www.youtube.com/watch?v=0K9NJHXYSm4', group: 2},
    { title: 'Elevação Frontal Halteres Peg Supinada', video: 'https://www.youtube.com/watch?v=DuUh84gcaso', group: 2},
    { title: 'Elevação Frontal Halteres Peg Neutra', video: 'https://www.youtube.com/watch?v=kQTNDsaEIKc', group: 2},
    { title: 'Elevação Frontal Cross Peg Pronada', video: 'https://www.youtube.com/watch?v=mOTjgenwgUc', group: 2},
    { title: 'Elevação Frontal Cross Peg Supinada', video: 'https://www.youtube.com/watch?v=lL8hIRuFcnU', group: 2},
    { title: 'Elevação Frontal Cross Corda', video: 'https://www.youtube.com/watch?v=xCQLo6LcudM', group: 2},
    { title: 'Elevação Frontal Anilha', video: 'https://www.youtube.com/watch?v=5bdlcZZvpzE', group: 2},
    { title: 'Elevação Frontal Cruzada', video: 'https://www.youtube.com/watch?v=btAEYSe5kp0', group: 2},
    { title: 'Crucifixo Inverso Halteres', video: 'https://www.youtube.com/watch?v=SLQZOByDo04', group: 2},
    { title: 'Crucifixo Inverso Cross', video: 'https://www.youtube.com/watch?v=gWa5abtK4G4', group: 2},
    { title: 'Desenvolvimento Halteres', video: 'https://www.youtube.com/watch?v=4pU-kV-OaVU', group: 2},
    { title: 'Desenvolvimento Anterior', video: 'https://www.youtube.com/watch?v=V_15VvJ3mr4', group: 2},
    { title: 'Desenvolvimento Posterior', video: 'https://www.youtube.com/watch?v=WIlm9oHEEq8', group: 2},
    { title: 'Desenvolvimento Militar', video: 'https://www.youtube.com/watch?v=urj7vgvfojk', group: 2},
    { title: 'Desenvolvimento Smith', video: 'https://www.youtube.com/watch?v=oi18jaIbFRM', group: 2},
    { title: 'Desenvolvimento Máquina', video: 'https://www.youtube.com/watch?v=oBF4YIwh_w8', group: 2},
    { title: 'Manguito Rotador Externo Barra', video: 'https://www.youtube.com/watch?v=QdUn8TBdjvU', group: 2},
    { title: 'Manguito Rotador Externo Halteres', video: 'https://www.youtube.com/watch?v=2ecstA3a5f4', group: 2},
    { title: 'Encolhimento Barra Anterior', video: 'https://www.youtube.com/watch?v=FutT8_yYJ58', group: 3},
    { title: 'Encolhimento Barra Posterior', video: 'https://www.youtube.com/watch?v=Y4w7ZZW84eM', group: 3},
    { title: 'Encolhimento Halteres', video: 'https://www.youtube.com/watch?v=ZzJ3zelC0qI', group: 3},
    { title: 'Encolhimento Smith Anterior', video: 'https://www.youtube.com/watch?v=5DQl_71T8iI', group: 3},
    { title: 'Encolhimento Smith Posterior', video: 'https://www.youtube.com/watch?v=7Ui8zi1w5A4', group: 3},
    { title: 'Remada Alta Halteres', video: 'https://www.youtube.com/watch?v=hFMCum41W9c', group: 3},
    { title: 'Remada Alta Barra', video: 'https://www.youtube.com/watch?v=Z6jSLKXZ0Ag', group: 3},
    { title: 'Remada Alta Cross', video: 'https://www.youtube.com/watch?v=dHjEyNaCmn0', group: 3},
    { title: 'Remada Alta Smith', video: 'https://www.youtube.com/watch?v=lD_zvmzP1K0', group: 3},
    { title: 'Paralelas', video: 'https://www.youtube.com/watch?v=8ZhWzT-V54Q', group: 4},
    { title: 'Mergulho', video: 'https://www.youtube.com/watch?v=jAkRzFnEvSo', group: 4},
    { title: 'Supino Fechado', video: 'https://www.youtube.com/watch?v=qJGw6CnVh2Q', group: 4},
    { title: 'Rosca Testa Barra Peg Pronada', video: 'https://www.youtube.com/watch?v=orMEOzQjiAs', group: 4},
    { title: 'Rosca Testa Barra Peg Supinada', video: 'https://www.youtube.com/watch?v=D_wnqWbIrYs', group: 4},
    { title: 'Rosca Testa Halteres Peg Supinada', video: 'https://www.youtube.com/watch?v=OS8sz24YV1g', group: 4},
    { title: 'Rosca Testa Halteres Peg Neutra', video: 'https://www.youtube.com/watch?v=KzKdkwIjZg8', group: 4},
    { title: 'Rosca Testa Halteres Peg Pronada', video: 'https://www.youtube.com/watch?v=esAavWMIRZ8', group: 4},
    { title: 'Tríceps Pulley Corda', video: 'https://www.youtube.com/watch?v=_KrR8248eLo', group: 4},
    { title: 'Tríceps Pulley Peg Pronada', video: 'https://www.youtube.com/watch?v=QDt8P44ORa4', group: 4},
    { title: 'Tríceps Pulley Peg Supinada', video: 'https://www.youtube.com/watch?v=2W09NaNpiOA', group: 4},
    { title: 'Tríceps Pulley Unilateral Peg Pronada', video: 'https://www.youtube.com/watch?v=TmO_85EK09I', group: 4},
    { title: 'Tríceps Pulley Unilateral Peg Supinada', video: 'https://www.youtube.com/watch?v=iO5EOd9Xe4c', group: 4},
    { title: 'Rosca Francesa Anilha', video: 'https://www.youtube.com/watch?v=D2oQJTz-RCA', group: 4},
    { title: 'Rosca Francesa Barra Peg Pronada', video: 'https://www.youtube.com/watch?v=fcIzvqXOJzs', group: 4},
    { title: 'Rosca Francesa Barra Peg Supinada', video: 'https://www.youtube.com/watch?v=xnP-A7ig8No', group: 4},
    { title: 'Rosca Francesa Halteres Peg Neutra', video: 'https://www.youtube.com/watch?v=aI8x4pHiByU', group: 4},
    { title: 'Rosca Francesa Halteres Peg Supinada', video: 'https://www.youtube.com/watch?v=KoLqZRyZuuU', group: 4},
    { title: 'Rosca Francesa Cross Corda	https://youtu.be/QhJ67UyNdsc', group: 4},
    { title: 'Rosca Francesa Halteres Peg Pronada', video: 'https://www.youtube.com/watch?v=DCbDClEDQvQ', group: 4},
    { title: 'Rosca Francesa Cross Corda', video: 'https://www.youtube.com/watch?v=QhJ67UyNdsc', group: 4},
    { title: 'Tríceps Coice Bilateral Halteres', video: 'https://www.youtube.com/watch?v=lbYQgZvJApA', group: 4},
    { title: 'Tríceps Coice Unilateral Halteres', video: 'https://www.youtube.com/watch?v=I4hzS9nYlgs', group: 4},
    { title: 'Tríceps Coice Unilateral Cross', video: 'https://www.youtube.com/watch?v=MGlqvfSCWLQ', group: 4},
    { title: 'Flexão De Braço Fechada', video: 'https://www.youtube.com/watch?v=9qT4QxmIuuU', group: 4},
    { title: 'Rosca Direta Barra Reta ou Barra W', video: 'https://www.youtube.com/watch?v=po8ibB0yY0Q', group: 5},
    { title: 'Rosca Direta Halteres', video: 'https://www.youtube.com/watch?v=ilyxkSNoyL8', group: 5},
    { title: 'Rosca Direta Cross', video: 'https://www.youtube.com/watch?v=_t2nQjiyboo', group: 5},
    { title: 'Rosca Martelo Barra H', video: 'https://www.youtube.com/watch?v=4YbWsz77mfc', group: 5},
    { title: 'Rosca Martelo Halteres', video: 'https://www.youtube.com/watch?v=KnymofpyiIQ', group: 5},
    { title: 'Rosca Martelo Corda Cross', video: 'https://www.youtube.com/watch?v=TXYeSl2QT50', group: 5},
    { title: 'Rosca Alternada Halteres', video: 'https://www.youtube.com/watch?v=v15BcmivG8g', group: 5},
    { title: 'Rosca Alternada Cross-Over', video: 'https://www.youtube.com/watch?v=LiiNiYF4lPY', group: 5},
    { title: 'Rosca Scott Halteres', video: 'https://www.youtube.com/watch?v=WbHASg1d29w', group: 5},
    { title: 'Rosca Scott Barra ou Barra W', video: 'https://www.youtube.com/watch?v=wQRRqKu9g7U', group: 5},
    { title: 'Rosca Scott Máquina', video: 'https://www.youtube.com/watch?v=3GfAZv126D0', group: 5},
    { title: 'Rosca Concentrada', video: 'https://www.youtube.com/watch?v=Cryg5VkGQBw', group: 5},
    { title: 'Rosca Concentrada Martelo', video: 'https://www.youtube.com/watch?v=ysjKbVT6-FQ', group: 5},
    { title: 'Flexão de Punho Barra Sentado', video: 'https://www.youtube.com/watch?v=pfNPsnjVWb4', group: 6},
    { title: 'Extensão de Punho Barra Sentado', video: 'https://www.youtube.com/watch?v=gHY5opbOhNE', group: 6},
    { title: 'Extensão de Punho Barra Em Pé', video: 'https://www.youtube.com/watch?v=guTTkQcy8jU', group: 6},
    { title: 'Extensão de Punho Cross', video: 'https://www.youtube.com/watch?v=SYHfATlt7LI', group: 6},
    { title: 'Flexão de Punho Cross', video: 'https://www.youtube.com/watch?v=4_Zf2r-2rAo', group: 6},
    { title: 'Rotacional de Punho', video: 'https://www.youtube.com/watch?v=MZ8y2hqjHxQ', group: 6},
    { title: 'Rosca Inversa Barra', video: 'https://www.youtube.com/watch?v=G1L3eV-a7gg', group: 6},
    { title: 'Rosca Inversa Cross', video: 'https://www.youtube.com/watch?v=0587NfWzEec', group: 6},
    { title: 'Rosca Inversa Alternada', video: 'https://www.youtube.com/watch?v=k86sqzLgiwY', group: 6},
    { title: 'Flexão de Punho Barra Em Pé', video: 'https://www.youtube.com/watch?v=PF1w-a7yQus', group: 6},
    { title: 'Agachamento Livre', video: 'https://www.youtube.com/watch?v=4TG8JdU6NPU', group: 7},
    { title: 'Agachamento Livre Frontal', video: 'https://www.youtube.com/watch?v=fJtI1_eUb2g', group: 7},
    { title: 'Agachamento Hack', video: 'https://www.youtube.com/watch?v=QZglgfUQZdk', group: 7},
    { title: 'Agachamento Smith', video: 'https://www.youtube.com/watch?v=4vA727LveHQ', group: 7},
    { title: 'Agachamento Smith Frontal', video: 'https://www.youtube.com/watch?v=_lPh4iHfvXA', group: 7},
    { title: 'Agachamento Halteres', video: 'https://www.youtube.com/watch?v=CROT8O8X_u0', group: 7},
    { title: 'Agachamento Adutores', video: 'https://www.youtube.com/watch?v=T64bNYs5-gI', group: 7},
    { title: 'Passada Barra', video: 'https://www.youtube.com/watch?v=q8oWAsKvdT0', group: 7},
    { title: 'Passada Halteres', video: 'https://www.youtube.com/watch?v=PCSEZejLkjk', group: 7},
    { title: 'Afundos Barra', video: 'https://www.youtube.com/watch?v=YoQL-sR3kFo', group: 7},
    { title: 'Afundos Halteres', video: 'https://www.youtube.com/watch?v=vj7uUw_5HYY', group: 7},
    { title: 'Afundos Smith', video: 'https://www.youtube.com/watch?v=0YjOOxFc7fY', group: 7},
    { title: 'Cadeira Extensora', video: 'https://www.youtube.com/watch?v=1f1DjMr68hY', group: 7},
    { title: 'Mesa Flexora', video: 'https://www.youtube.com/watch?v=OMKhQ2O11fc', group: 7},
    { title: 'Cadeira Flexora', video: 'https://www.youtube.com/watch?v=n8j1X_xByD4', group: 7},
    { title: 'Flexor Vertical', video: 'https://www.youtube.com/watch?v=HGoN-nfJFGE', group: 7},
    { title: 'Leg Press', video: 'https://www.youtube.com/watch?v=kyESFAj3W0E', group: 7},
    { title: 'Leg Press Adutores', video: 'https://www.youtube.com/watch?v=1kjxuWNPBUc', group: 7},
    { title: 'Stiff Barra', video: 'https://www.youtube.com/watch?v=Xgql23RkpBk', group: 7},
    { title: 'Stiff Halteres', video: 'https://www.youtube.com/watch?v=mNsSgOKopbE', group: 7},
    { title: 'Stiff Smith', video: 'https://www.youtube.com/watch?v=QDLNogcXvHU', group: 7},
    { title: 'Agachamento Bulgaro Halteres', video: 'https://www.youtube.com/watch?v=WyMsCylTcKM', group: 7},
    { title: 'Agachamento Bulgaro Barra', video: 'https://www.youtube.com/watch?v=wENBoTTRDa8', group: 7},
    { title: 'Cadeira Adutora', video: 'https://www.youtube.com/watch?v=UB5qna8tQkw', group: 7},
    { title: '4 Apoios Joelho Estendido', video: 'https://www.youtube.com/watch?v=C1LK-ca840k', group: 8},
    { title: '4 Apoios Joelho Flexionado', video: 'https://www.youtube.com/watch?v=3H_WSx0dK-I', group: 8},
    { title: 'Glúteos Graviton', video: 'https://www.youtube.com/watch?v=F2yGtpW4J4s', group: 8},
    { title: 'Glúteos Máquina', video: 'https://www.youtube.com/watch?v=A68gT5W_J50', group: 8},
    { title: 'Glúteos Smith', video: 'https://www.youtube.com/watch?v=PMbVxKqNM7I', group: 8},
    { title: 'Glúteos Cross', video: 'https://www.youtube.com/watch?v=vgjt9LUm6Jg', group: 8},
    { title: 'Elevação Pélvica Barra', video: 'https://www.youtube.com/watch?v=jqgDVIv581k', group: 8},
    { title: 'Elevação Pélvica Halter', video: 'https://www.youtube.com/watch?v=XNbfCoWFcFs', group: 8},
    { title: 'Elevação Pélvica Anilha', video: 'https://www.youtube.com/watch?v=0lPFQdMtNBU', group: 8},
    { title: 'Elevação Pélvica Smith', video: 'https://www.youtube.com/watch?v=0I3xQYtPCGQ', group: 8},
    { title: 'Cadeira Abdutora', video: 'https://www.youtube.com/watch?v=yVZ0Vs7j6EM', group: 8},
    { title: 'Gêmeos Em Pé Máquina', video: 'https://www.youtube.com/watch?v=hlQbAQB61_Y', group: 9},
    { title: 'Gêmeos Em Pé Hack', video: 'https://www.youtube.com/watch?v=GAn7R1U3EDw', group: 9},
    { title: 'Gêmeos Em Pé Smith', video: 'https://www.youtube.com/watch?v=ER72bXEam4c', group: 9},
    { title: 'Gêmeos Em Pé Livre', video: 'https://www.youtube.com/watch?v=VMa37XJdejk', group: 9},
    { title: 'Gêmeos Sentado Máquina', video: 'https://www.youtube.com/watch?v=gBIxBWBorB8', group: 9},
    { title: 'Gêmeos Sentado Smith', video: 'https://www.youtube.com/watch?v=iK6cVWR3-jI', group: 9},
    { title: 'Gêmeos Sentado Livre', video: 'https://www.youtube.com/watch?v=CiFlAqIx-lY', group: 9},
    { title: 'Gêmeos Leg Press', video: 'https://www.youtube.com/watch?v=omdVB4rQnoQ', group: 9},
    { title: 'Gêmeos Em Pé Unilateral', video: 'https://www.youtube.com/watch?v=BPpM8bq-LqM&feature=youtu.be', group: 9},
    { title: 'Gêmeos Burrinho', video: 'https://www.youtube.com/watch?v=BPpM8bq-LqM&feature=youtu.be', group: 9},
    { title: 'Gêmeos Cócoras', video: 'https://www.youtube.com/watch?v=BPpM8bq-LqM&feature=youtu.be', group: 9},
    { title: 'Supra', video: 'https://www.youtube.com/watch?v=N5SL7rhM07c', group: 10},
    { title: 'Infra', video: 'https://www.youtube.com/watch?v=8slFJ9J31lM', group: 11},
    { title: 'Oblíquos', video: 'https://www.youtube.com/watch?v=k9rfQiXoM1w', group: 11},
    { title: 'Prancha', video: 'https://www.youtube.com/watch?v=TxadpmTHK08', group: 11},
    { title: 'Extensão Lombar', video: 'https://www.youtube.com/watch?v=Jto980puQ3c', group: 12},
    { title: 'Drop-Set 3x', video: 'https://youtu.be/SwWD2kNBj3Q', group: 12},
    { title: `Rest 'n' Pause 3x`, video: 'https://youtu.be/VByUblTMiI8', group: 12},
    { title: 'FST-7', video: 'https://youtu.be/7UUHsixTRgo', group: 12},
    { title: 'GVT', video: 'https://youtu.be/O0p7RTmFzGM', group: 12},
    { title: 'Bi-Set', video: 'https://youtu.be/bd0V7svOP0E', group: 12}
].map(data => ({...data, group: groups[data.group]}));
